### ISSUE TITLE
Can't seem to get this to work

### ISSUE THREAD

**Issue by stevarino** [coderaiser/mock-import#2]
I'm attempting to mock some modules, not for testing reasons but because of environmental runtime availability reasons. Specifically the @minecraft/server module and related ilk (https://www.npmjs.com/package/@minecraft/server) as these modules are only available from within a running Minecraft Addon.

Code being run:

```
//@ts-ignore
import { createMockImport, enableNestedImports } from 'mock-import';

// import { world, system, Entity } from "@minecraft/server";
// import * as ui from "@minecraft/server-ui";

const { mockImport, reImport, stopAll } = createMockImport(import.meta.url);

type DiscussionModule = {Discussion: {actions: {[action: string]: unknown}}};

export async function getDiscussionActions() {
  mockImport('@minecraft/server', {
    system: {},
    world: {},
    Entity: {},
    Player: {},
  });
  
  mockImport('@minecraft/server-ui', {
    ActionFormData: {},
  });
  
  mockImport('@minecraft/server-net', {
  });
  
  mockImport('@minecraft/server-admin', {
    variables: {},
  });
  
  //@ts-ignore
  const cache = (global.__mockImportCache) as Map<string, unknown>;
  console.log('CACHE: ', [...cache.keys()]);
  const { Discussion } = await reImport('../behavior_pack/src/dialogue/discussion.js') as DiscussionModule;
  // these mutate Discussion.actions as a side-effect
  await reImport('../behavior_pack/src/bots.js');
  await reImport('../behavior_pack/src/dialogue/actions.js');
  return [...Object.keys(Discussion.actions)];
}
```

Trimmed output:

```
CACHE:  [
  '@minecraft/server',
  '@minecraft/server-ui',
  '@minecraft/server-net',
  '@minecraft/server-admin'
]
node:internal/modules/cjs/loader:1090
  const err = new Error(message);
              ^

Error: Cannot find module '@minecraft/server-ui'
Require stack:
- /home/stevarino/projects/bds-hub/dist/behavior_pack/src/dialogue/discussion.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1090:15)
    at resolve (node:internal/modules/helpers:125:19)
    at file:///home/stevarino/projects/bds-hub/node_modules/mock-import/lib/is-in-cache.js:3:22
    at ImportDeclaration (file:///home/stevarino/projects/bds-hub/node_modules/mock-import/lib/convert-imports/plugin-convert-to-absolute/index.js:16:32)
    at NodePath._call (/home/stevarino/projects/bds-hub/node_modules/@putout/babel/bundle/babel.cjs:40821:20)
    at NodePath.call (/home/stevarino/projects/bds-hub/node_modules/@putout/babel/bundle/babel.cjs:40811:17)
    at NodePath.visit (/home/stevarino/projects/bds-hub/node_modules/@putout/babel/bundle/babel.cjs:40855:31)
    at TraversalContext.visitQueue (/home/stevarino/projects/bds-hub/node_modules/@putout/babel/bundle/babel.cjs:42250:16)
    at TraversalContext.visitMultiple (/home/stevarino/projects/bds-hub/node_modules/@putout/babel/bundle/babel.cjs:42225:17)
    at TraversalContext.visit (/home/stevarino/projects/bds-hub/node_modules/@putout/babel/bundle/babel.cjs:42271:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/stevarino/projects/bds-hub/dist/behavior_pack/src/dialogue/discussion.js'
  ]
}
```

So I can see that the modules exist within the cache, but they are failing to load.

Here's what the javascript import (compiled from typescript) from `dist/behavior_pack/src/dialogue/discussion.js` looks like:

```
import { ActionFormData } from "@minecraft/server-ui";
```

Anyway I'm not sure what I'm doing wrong here, any assistance would be appreciated. Thanks!

**Comment by coderaiser** [comment]
How do you run your tests? Mock Import should be passed as `—-loader` to get things working.

**Comment by stevarino** [comment]
I believe I am running it correctly with --loader - the traceback shows mock-import in it's call path for the failed import.

And I'm not using it for testing but rather inspection/reflection of code that references libraries not available to me.

**Comment by coderaiser** [comment]
Could you please provide minimal reproducible example. What version of node are you using?
The thing is ESM loaders is still experimental feature, and it works differently in different versions of node.js, so if it is `v16, or `v18` you better use previous major version.

**Comment by stevarino** [comment]
Sorry I ended up using the typescript api to parse the code for the info I need. Feel free to close this.
